### ISSUE TITLE
Skip nested markup containers 

### ISSUE THREAD

**Issue by monospaced** [simon360/react-from-markup#33]
Currently nesting markup containers like this could lead to buggy behaviour:

```html
<div data-react-from-markup-container>
  <div data-rehydratable="HatComponent">…</div>
  <div data-react-from-markup-container>
    <div data-rehydratable="ShoesComponent">…</div>
  </div>
</div>
```
Add a check to skip markup containers if they are inside a parent container, potentially something like:

```js
roots.some(r => r.contains(root)
```

**Comment by willtonkin** [comment]
I'm taking at a look at this now, PR to follow
